import 'dotenv/config';
import express from 'express'; import http from 'node:http'; import helmet from 'helmet'; import rateLimit from 'express-rate-limit'; import {Server} from 'socket.io'; import pg from 'pg'; import bcrypt from 'bcryptjs'; import crypto from 'node:crypto'; import fs from 'node:fs/promises';
import {makeBag} from './game/rules.js'; import {hashPassword,verifyPassword,validPassword,code,digest} from './auth.js';
import {registerSocialApi,registerGameSockets} from './social.js';
const {Pool}=pg; const app=express(); const server=http.createServer(app); const io=new Server(server,{cors:{origin:false}}); const pool=new Pool({connectionString:process.env.DATABASE_URL});
app.use(helmet({contentSecurityPolicy:false})); app.use(rateLimit({windowMs:15*60*1000,max:300,standardHeaders:true})); app.use(express.json({limit:'100kb'})); app.use(express.static('public'));
const sessions=new Map(); const pending=new Map();
function sid(req,res){let s=req.headers.cookie?.match(/mathable_session=([^;]+)/)?.[1];if(!s){s=crypto.randomBytes(32).toString('hex');res.setHeader('Set-Cookie',`mathable_session=${s}; HttpOnly; SameSite=Lax; Path=/; ${process.env.NODE_ENV==='production'?'Secure;':''}`)}return s}
function auth(req,res,next){const s=req.headers.cookie?.match(/mathable_session=([^;]+)/)?.[1],u=s&&sessions.get(s);if(!u)return res.status(401).json({error:'authentification_requise'});req.user=u;next()}
async function sendCode(email,c){if(process.env.SMTP_HOST){const nodemailer=(await import('nodemailer')).default;const t=nodemailer.createTransport({host:process.env.SMTP_HOST,port:Number(process.env.SMTP_PORT||587),secure:Number(process.env.SMTP_PORT)===465,auth:{user:process.env.SMTP_USER,pass:process.env.SMTP_PASS}});await t.sendMail({from:process.env.SMTP_FROM,to:email,subject:'Code Mathable',text:`Votre code Mathable : ${c}. Expire dans 15 minutes.`})}else console.log(`[DEV] Code Mathable pour ${email}: ${c}`)}
app.post('/api/auth/register',async(req,res)=>{try{const email=String(req.body.email||'').trim().toLowerCase(),username=String(req.body.username||'').trim().toLowerCase(),password=String(req.body.password||'');if(!email.includes('@')||!/^[a-z0-9_]{3,20}$/.test(username)||!validPassword(password))return res.status(400).json({error:'inscription_invalide'});const h=await hashPassword(password),r=await pool.query('INSERT INTO users(email,username,password_hash) VALUES($1,$2,$3) RETURNING id,email',[email,username,h]);const c=code();await pool.query('INSERT INTO verification_codes(user_id,purpose,code_hash,expires_at) VALUES($1,$2,$3,now()+interval \'15 minutes\')',[r.rows[0].id,'verify',digest(c)]);await sendCode(email,c);res.status(201).json({message:'code_envoye'})}catch(e){res.status(400).json({error:'email_ou_pseudo_deja_utilise_ou_base_indisponible'})}});
app.post('/api/auth/verify',async(req,res)=>{const email=String(req.body.email||'').toLowerCase(),c=String(req.body.code||'');const r=await pool.query('SELECT u.id,vc.id code_id,vc.code_hash,vc.attempts FROM users u JOIN verification_codes vc ON vc.user_id=u.id WHERE u.email=$1 AND vc.purpose=\'verify\' AND vc.used_at IS NULL AND vc.expires_at>now() ORDER BY vc.id DESC LIMIT 1',[email]);if(!r.rowCount||r.rows[0].attempts>=5)return res.status(400).json({error:'code_expire_ou_bloque'});await pool.query('UPDATE verification_codes SET attempts=attempts+1 WHERE id=$1',[r.rows[0].code_id]);if(digest(c)!==r.rows[0].code_hash)return res.status(400).json({error:'code_incorrect'});await pool.query('UPDATE users SET verified=true WHERE id=$1',[r.rows[0].id]);await pool.query('UPDATE verification_codes SET used_at=now() WHERE id=$1',[r.rows[0].code_id]);res.json({message:'compte_valide'})});
app.post('/api/auth/login',async(req,res)=>{const email=String(req.body.email||'').toLowerCase(),r=await pool.query('SELECT * FROM users WHERE email=$1',[email]);if(!r.rowCount||!r.rows[0].verified||!(await verifyPassword(String(req.body.password||''),r.rows[0].password_hash)))return res.status(401).json({error:'identifiants_invalides'});const s=sid(req,res);sessions.set(s,{id:r.rows[0].id,email,username:r.rows[0].username});res.json({email,username:r.rows[0].username})});
app.post('/api/auth/logout',(req,res)=>{const s=req.headers.cookie?.match(/mathable_session=([^;]+)/)?.[1];if(s)sessions.delete(s);res.setHeader('Set-Cookie','mathable_session=; Max-Age=0; HttpOnly; SameSite=Lax; Path=/');res.json({ok:true})});
registerSocialApi(app,{pool,auth});
app.get('/api/health',(req,res)=>res.json({ok:true,bag:makeBag().length}));
registerGameSockets(io,{pool,sessions});
async function boot(){try{await pool.query(await fs.readFile(new URL('../migrations/001_init.sql',import.meta.url),'utf8'));}catch(e){console.error('Migration PostgreSQL impossible:',e.message)}const port=Number(process.env.PORT||3000);server.listen(port,()=>console.log(`Mathable écoute sur ${port}`));}boot();
